apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutor-tracker-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - apps.emptydesign.com
      secretName: tutor-tracker-tls
  rules:
    - host: apps.emptydesign.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tutor-tracker-service
                port:
                  number: 80
